version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./compositions/database:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@e2ee.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:8080"

  redis:
    image: redis
    container_name: redis_container
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: